dist: bionic

sudo: required

language: shell

services: 
  - docker

env:
  global:
    - KANCLOUD_USER=willseecloud

before_install:
  - openssl aes-256-cbc -K $encrypted_32f56afb6050_key -iv $encrypted_32f56afb6050_iv -in secrets/rclone.conf.enc -out rclone.conf -d

install:
  - |
    count=$(cat repo.list | wc -l)
    icount=1
    for repo in `cat repo.list`
    do
      echo [$icount/$count]: $repo
      git clone https://${KANCLOUD_USER}:${KANCLOUD_PASS}@git.kancloud.cn/${KANCLOUD_USER}/${repo}.git ${PWD}/bak/${repo}
      ((icount++))
    done
script:
  - docker run --rm -v $PWD/secrets:/config/rclone -v ${PWD}/bak:/bak -w /bak rclone/rclone sync "/bak/*" gcloud_drive:/kancloudbak/
