dist: bionic

sudo: required

language: shell

services: 
  - docker

env:
  global:
    - KANCLOUD_USER=willseecloud
    - CLONE_DIR=${PWD}/bak

before_install:
  - openssl aes-256-cbc -K $encrypted_749dcc9e92f7_key -iv $encrypted_749dcc9e92f7_iv -in secrets/credentials.json.enc -out secrets/credentials.json -d
  - openssl aes-256-cbc -K $encrypted_0359594a79a5_key -iv $encrypted_0359594a79a5_iv -in secrets/token.json.enc -out secrets/token.json -d

install:
  - |
    count=$(cat repo.list | wc -l)
    icount=1
    for repo in `cat repo.list`
    do
      echo [$icount/$count]: $repo
      git clone https://${KANCLOUD_USER}:${KANCLOUD_PASS}@git.kancloud.cn/${KANCLOUD_USER}/${repo}.git ${CLONE_DIR}/${repo}
      tar -jcf ${CLONE_DIR}/${repo}.tar.bz2 -C ${CLONE_DIR}/${repo} .
      ((icount++))
    done

script:
  - docker run --rm -v $PWD/secrets:/app/secrets:ro -v ${CLONE_DIR}:/bak/:rw d0whc3r/gdrive -b /bak/*.bz2 -z kancloud_bak_`date '+%Y%m%d%H%M%S'`.zip -f kancloudbak -c -r
  - docker run --rm -v $PWD/secrets:/app/secrets:ro d0whc3r/gdrive -d kancloudbak=1M

