dist: bionic

sudo: required

language: shell

services: 
  - docker

env:
  global:
    - KANCLOUD_USER=willseecloud

before_install:
  - openssl aes-256-cbc -K $encrypted_749dcc9e92f7_key -iv $encrypted_749dcc9e92f7_iv -in secrets/credentials.json.enc -out secrets/credentials.json -d
  - openssl aes-256-cbc -K $encrypted_0359594a79a5_key -iv $encrypted_0359594a79a5_iv -in secrets/token.json.enc -out secrets/token.json -d

install:
  - |
    repos=$(cat repo.list)
    count=$(echo "$repos" | wc -l)
    icount=1
    mkdir -p ${PWD}/kancloud/
    for repo in $repos
    do
      echo [$icount/$count]: $repos
      git clone https://${KANCLOUD_USER}:${KANCLOUD_PASS}@git.kancloud.cn/${KANCLOUD_USER}/${repo}.git ${PWD}/kancloud/
      ((icount++))
    done

after_script:
  - docker run --rm -v $PWD/secrets:/app/secrets:ro gdrive -b ${PWD}/kancloud/* -z kancloud_bak.zip -f kancloud-c -r
  - docker run --rm -v $PWD/secrets:/app/secrets:ro gdrive -d kancloud=2d -d monthly=1M
