dist: bionic

sudo: required

language: shell

services: 
  - docker

env:
  global:
    - KANCLOUD_USER=willseecloud
    - CLONE_DIR=${PWD}/bak

before_install:
  - openssl aes-256-cbc -K $encrypted_32f56afb6050_key -iv $encrypted_32f56afb6050_iv -in rclone/rclone.conf.enc -out rclone/rclone.conf -d

install:
  - |
    count=$(cat repo.list | wc -l)
    icount=1
    for repo in `cat repo.list`
    do
      echo [$icount/$count]: $repo
      git clone https://${KANCLOUD_USER}:${KANCLOUD_PASS}@git.kancloud.cn/${KANCLOUD_USER}/${repo}.git ${CLONE_DIR}/${repo}
      tar -jcf ${CLONE_DIR}/${repo}.tar.bz2 -C ${CLONE_DIR}/${repo} .
      ((icount++))
    done
script:
  - docker run --rm -v $PWD/rclone:/config/rclone/ -v ${CLONE_DIR}:/data:shared rclone/rclone sync . gcloud_drive:/kancloudbak -v
